---
development:
  # cloud_name: dewdtthcr
  # api_key: '958532245147856'
  # api_secret: Pa5S6coEIjA9Y3CoBRrQjDqC5jk
  # enhance_image_tag: true
  cloud_name: dkhyavsqw
  api_key: '962253128593789'
  api_secret: DZBdFOunks7S46ONAilbs0xnsFE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dkhyavsqw
  api_key: '962253128593789'
  api_secret: DZBdFOunks7S46ONAilbs0xnsFE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dkhyavsqw
  api_key: '962253128593789'
  api_secret: DZBdFOunks7S46ONAilbs0xnsFE
  enhance_image_tag: true
  static_image_support: false
